### ISSUE TITLE
Transaction too large on calendar

### ISSUE THREAD

**Issue by nijel** [bitfireAT/davdroid#274]
When trying to sync calendar, I get following error:

```
D/davdroid.LocalCollection(14837): Committing 1949 operations
E/JavaBinder(14837): !!! FAILED BINDER TRANSACTION !!!
E/davdroid.DavSyncAdapter(14837): Local storage (content provider) exception
E/davdroid.DavSyncAdapter(14837): at.bitfire.davdroid.resource.LocalStorageException: Couldn't access local content provider
E/davdroid.DavSyncAdapter(14837): 	at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:314)
E/davdroid.DavSyncAdapter(14837): 	at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:193)
E/davdroid.DavSyncAdapter(14837): 	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:87)
E/davdroid.DavSyncAdapter(14837): 	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:129)
E/davdroid.DavSyncAdapter(14837): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
E/davdroid.DavSyncAdapter(14837): Caused by: android.os.TransactionTooLargeException
E/davdroid.DavSyncAdapter(14837): 	at android.os.BinderProxy.transact(Native Method)
E/davdroid.DavSyncAdapter(14837): 	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:521)
E/davdroid.DavSyncAdapter(14837): 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
E/davdroid.DavSyncAdapter(14837): 	at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:311)
E/davdroid.DavSyncAdapter(14837): 	... 4 more
I/davdroid.DavSyncAdapter(14837): Sync complete for com.android.calendar
D/davdroid.DavSyncAdapter(14837): Closing httpClient
```

The problem here is probably that the event has 1948 attendees, but that's not something I can control...

**Comment by rfc2822** [comment]
Splitting transactions > 1 MB and implementing meta-database logic is not within the scope of DAVdroid. Mobile devices have still limited resources, and that's why the transaction buffer is limited.

I'll close this issue for now, please follow up at https://code.google.com/p/android/issues/detail?id=73499 and comment there if that is an issue for you.
