### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid int: "T17H31M44"

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/davdroid#366]
Reported via Play Store:

```
java.lang.IllegalArgumentException: Invalid int: "T17H31M44"
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:160)
at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:512)
at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:311)
at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:194)
at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:88)
at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:134)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

DAVdroid 0.6.2 to 0.6.7.1, always Android 4.4 / Moto G (falcon_umts)

**Comment by rfc2822** [comment]
I guess there's no chance to find out what's wrong there without further information.
