### ISSUE TITLE
Sync problems with Posteo

### ISSUE THREAD

**Issue by koaoala** [bitfireAT/davdroid#392]
Hi!
I just found out that all my events on my fairphone calender are missing. Thus I checked DAVdroid  and found out that the account I use to synchronize my calender (a posteo-account) doesn't exist any longer. I tried to set it up again, but after entering all relevant information (following those steps: ahttps://posteo.de/hilfe/kalender-und-adressbuchabgleich-mit-davdroid-android) the app doesn't react when I press the top right arrow to continue. I restarted my phone but the problem remains just the same. 
BTW my events are still saved in the posteo-account, I can access them via my computer.
Any ideas?

Best regards,
Koa

**Comment by rfc2822** [comment]
Any news on this?

**Comment by koaoala** [comment]
No. I haven't received any answer from posteo.de yet. However, two "normal"
calendars work - only the birthday calendar doesn't...
Am 01.01.2015 21:06 schrieb "rfc2822" <notifications@github.com>:

**Comment by rfc2822** [comment]
Maybe the birthday calendar isn't a real calendar? Please note that you can sync your contact birthday information with a virtual calendar on your device with [Birthday Adapter](https://sufficientlysecure.org/index.php/android-apps/)

I'll close this issue for now. If there's anything new that indicates a DAVdroid problem, please post here again and I'll re-open the issue.

**Comment by paifgx** [comment]
I also have a problem with sync with Posteo. via logcat:

```
01-28 20:14:49.270  12742-12760/at.bitfire.davdroid:sync E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!
01-28 20:14:49.270  12742-12760/at.bitfire.davdroid:sync E/davdroid.DavSyncAdapter﹕ Local storage (content provider) exception
    at.bitfire.davdroid.resource.LocalStorageException: Couldn't access local content provider
            at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:315)
            at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:196)
            at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:90)
            at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:144)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
     Caused by: android.os.TransactionTooLargeException
            at android.os.BinderProxy.transact(Native Method)
            at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:517)
            at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
            at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:312)
            at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:196)
            at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:90)
            at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:144)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

**Comment by koaoala** [comment]
Hi.
Yes, two days ago I finally received an email from posteo support stating
that they have problems regarding reccuring dates. Thus it seems to be
really a posteo bug.
Thanks for your help!
Am 01.01.2015 21:06 schrieb "rfc2822" <notifications@github.com>:
