### ISSUE TITLE
DavMail 

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/davdroid#477]
DavMail doesn't work with DAVdroid, see https://twitter.com/davdroidapp/status/583948186374561792

Logs:

```
I/davdroid.SyncManager(15167): Fetching 1 new remote resource(s)
V/davdroid.URIUtils(15167): Normalized URL lol -> lol
E/davdroid.DavSyncAdapter(15167): Hard HTTP error 404
E/davdroid.DavSyncAdapter(15167): at.bitfire.davdroid.webdav.NotFoundException: 404 Not Found
E/davdroid.DavSyncAdapter(15167): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:415)
E/davdroid.DavSyncAdapter(15167): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:393)
E/davdroid.DavSyncAdapter(15167): 	at at.bitfire.davdroid.webdav.WebDavResource.get(WebDavResource.java:343)
E/davdroid.DavSyncAdapter(15167): 	at at.bitfire.davdroid.resource.RemoteCollection.get(RemoteCollection.java:138)
E/davdroid.DavSyncAdapter(15167): 	at at.bitfire.davdroid.resource.RemoteCollection.multiGet(RemoteCollection.java:94)
E/davdroid.DavSyncAdapter(15167): 	at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:193)
E/davdroid.DavSyncAdapter(15167): 	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:90)
E/davdroid.DavSyncAdapter(15167): 	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:146)
E/davdroid.DavSyncAdapter(15167): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
I/davdroid.DavSyncAdapter(15167): Sync complete for com.android.calendar
D/SyncManager( 2275): failed sync operation unterwaditzer07@students.fadi.at u0 (bitfire.at.davdroid), com.android.calendar, USER, latestRunTime 366250168, reason: 1000, SyncResult: stats [ numParseExceptions: 1]
D/SyncManager( 2275): not retrying sync operation because the error is a hard error: unterwaditzer07@students.fadi.at u0 (bitfire.at.davdroid), com.android.calendar, USER, latestRunTime 366253297, reason: 1000
D/davdroid.DavSyncAdapter(15167): Closing httpClient
W/ResourceType( 2437): No known package when getting value for resource number 0x62020025
W/StatusBarIconView( 2437): Icon not found in 2130837511: 7f020007
W/StatusBarIconView( 2437): No icon for slot at.bitfire.davdroid/0x621c92fa
W/StatusBar( 2437): removeNotification for unknown key: android.os.BinderProxy@424222a0
D/NotificationService( 2275): onNotification error pkg=at.bitfire.davdroid tag=null id=1646039802; will crashApplication(uid=10290, pid=15167)
D/AndroidRuntime(15167): Shutting down VM
W/dalvikvm(15167): threadid=1: thread exiting with uncaught exception (group=0x419afce0)
W/StatusBar( 2437): removeNotification for unknown key: android.os.BinderProxy@424222a0
E/AndroidRuntime(15167): FATAL EXCEPTION: main
E/AndroidRuntime(15167): Process: at.bitfire.davdroid:sync, PID: 15167
E/AndroidRuntime(15167): android.app.RemoteServiceException: Bad notification posted from package at.bitfire.davdroid: Couldn't create icon: StatusBarIcon(pkg=at.bitfire.davdroiduser=0 id=0x7f020007 level=0 visible=true num=0 )
E/AndroidRuntime(15167): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1372)
E/AndroidRuntime(15167): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(15167): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(15167): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(15167): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15167): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(15167): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(15167): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(15167): 	at dalvik.system.NativeStart.main(Native Method)
W/DropBoxManagerService( 2275): Dropping: data_app_crash (905 > 0 bytes)
```

```
Request:

    PROPFIND /users/unterwaditzer07@students.fadi.at/calendar/

    <propfind xmlns="DAV:">
       <prop>
          <CS:getctag xmlns:CS="http://calendarserver.org/ns/"/>
          <getetag/>
       </prop>
    </propfind>

Response:

    <?xml version="1.0" encoding="UTF-8"?>
        <D:multistatus xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:E="urn:ietf:params:xml:ns:carddav">
            <D:response>
                <D:href>/users/unterwaditzer07@students.fadi.at/calendar/</D:href>
                <D:propstat>
                    <D:prop>
                        <D:getetag>2015-01-20T13:49:21Z</D:getetag>
                        <CS:getctag xmlns:CS="http://calendarserver.org/ns/">MjAxNS0wNC0wM1QxNToxODoyMFoyMDE1LTAzLTAzVDE2OjM1OjE0Wg==</CS:getctag>
                    </D:prop>
                    <D:status>HTTP/1.1 200 OK</D:status>
                </D:propstat>
            </D:response>
            <D:response>
                <D:href>/users/unterwaditzer07@students.fadi.at/calendar/20150403T151816Z-14271_f0be90541167f045.ics</D:href>
                <D:propstat>
                    <D:prop>
                        <D:getetag>2015-04-03T15:18:20Z</D:getetag>
                    </D:prop>
                    <D:status>HTTP/1.1 200 OK</D:status>
                </D:propstat>
            </D:response>
            <D:response>
                <D:href>/users/unterwaditzer07@students.fadi.at/calendar/lol/</D:href>
                <D:propstat>
                    <D:prop>
                        <D:getetag>2015-01-20T13:59:05Z</D:getetag>
                        <CS:getctag xmlns:CS="http://calendarserver.org/ns/">MjAxNS0wMy0wM1QxNjozNToxNFo=</CS:getctag>
                    </D:prop>
                    <D:status>HTTP/1.1 200 OK</D:status>
                </D:propstat>
            </D:response>
        </D:multistatus>
```

**Comment by untitaker** [comment]
The first log is distracting as it includes an exception that is not DAV-related.

**Comment by rfc2822** [comment]
@untitaker Have updated it now

**Comment by untitaker** [comment]
Reposting my comment because the pastebin I used auto-deletes after a while:

    You'll probably need the `getcontenttype` property to filter out collections.

**Comment by rfc2822** [comment]
> You'll probably need the `getcontenttype` property to filter out collections.

DAVdroid 0.8+ uses REPORT instead of PROPFIND, so that collections shouldn't be received. Would like to have that tested with DAVdroid 0.8+.

**Comment by untitaker** [comment]
Will try sometime.

**Comment by untitaker** [comment]
Calendar and contacts work perfectly, but VTODO seems completely unsupported.

**Comment by untitaker** [comment]
I think you can call DavMail supported by DavDroid and close this issue @rfc2822
