### ISSUE TITLE
Zimbra Shared Calendar fails on Redirect 302

### ISSUE THREAD

**Issue by carlosgds** [bitfireAT/davdroid#478]
Hi,

I've got a problem with DAVdroid (version 0.7.2 from F-Droid) and Zimbra 8.6.0GA when using a shared calendar between 2 users. I'm using a Nexus 7 with Android 5.1 (build: LMY47D)

* user "mainuser" shares a calendar (named MyCal) with user "otheruser" (also named MyCal)
* synchronizing works from mainuser --> otheruser
* otheruser creates a new event in MyCal
* synchronisation fails to write the result back

It seems that the redirect 302 from the server is not correctly handled by DAVdroid for this case (the standard redirect of the user's own calendar works fine).

The DAVdroid log is:
```
I/davdroid.DavSyncAdapter(10941): Performing sync for authority com.android.calendar
D/davdroid.DavSyncAdapter(10941): Creating new DavHttpClient
V/davdroid.TlsSniSocketFactory(10941): Setting allowed TLS protocols: TLSv1, TLSv1.1, TLSv1.2
I/davdroid.DavHttpClient(10941): Wire logging active, disabling HTTP compression
D/davdroid.DavSyncAdapter(10941): Server supports VCard version 3.0
V/davdroid.URIUtils(10941): Normalized URL https://mother.xxxxxxx.xx/dav/otheruser@xxxxxxx.xx/MyCal/ -> https://mother.xxxxxxx.xx/dav/otheruser@xxxxxxx.xx/MyCal/
D/davdroid.WebDavResource(10941): Using preemptive authentication (not compatible with Digest auth)
I/davdroid.SyncManager(10941): Remotely removing 0 deleted resource(s) (if not changed)
I/davdroid.SyncManager(10941): Uploading 1 new resource(s) (if not existing)
E/PhoneWindow( 5276): Circular progress bar not located in current window decor
V/davdroid.URIUtils(10941): Normalized URL 20150408T170109Z-10941_4933402f77a06876.ics -> 20150408T170109Z-10941_4933402f77a06876.ics
D/HttpClient(10941): Re-using cached 'basic' auth scheme for https://mother.xxxxxxx.xx:443
D/HttpClient(10941): Connection request: [route: HttpRoute[{s}->https://mother.xxxxxxx.xx:443]][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 3]
D/HttpClient(10941): Connection leased: [id: 0][route: HttpRoute[{s}->https://mother.xxxxxxx.xx:443]][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 3]
D/HttpClient(10941): Opening connection HttpRoute[{s}->https://mother.xxxxxxx.xx:443]
D/davdroid.DavSyncAdapter(10941): Closing httpClient
I/davdroid.DavSyncAdapter(10941): Performing sync for authority com.android.calendar
D/HttpClient(10941): Connecting to mother.xxxxxxx.xx/158.64.32.131:443
D/HttpClient(10941): Connecting socket to mother.xxxxxxx.xx/158.64.32.131:443 with timeout 20000
D/HttpClient(10941): Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]
D/HttpClient(10941): Enabled cipher suites:[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
D/HttpClient(10941): Enabling SNI for mother.xxxxxxx.xx
D/HttpClient(10941): Starting handshake
D/HttpClient(10941): Secure session established
D/HttpClient(10941):  negotiated protocol: TLSv1.2
D/HttpClient(10941):  negotiated cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
D/HttpClient(10941):  peer principal: OID.1.2.840.113549.1.9.1=#1616706F73746D6173746572406F6C696E6765722E6E6574, CN=mother.xxxxxxx.xx, O=AO, L=NNN, ST=Rheinland-Pfalz, C=DE, OID.2.5.4.13=VxtpVt7W1o5Gn6Tl
D/HttpClient(10941):  peer alternative names: [mother.xxxxxxx.xx, xxxxxxx.xx]
D/HttpClient(10941):  issuer principal: CN=StartCom Class 2 Primary Intermediate Server CA, OU=Secure Digital Certificate Signing, O=StartCom Ltd., C=IL
D/HttpClient(10941):  issuer alternative names: [http://www.startssl.com/]
D/HttpClient(10941): Connection established 10.2.100.9:37435<->158.64.32.131:443
D/HttpClient(10941): Executing request PUT /dav/otheruser@xxxxxxx.xx/MyCal/20150408T170109Z-10941_4933402f77a06876.ics HTTP/1.1
D/HttpClient(10941): Target auth state: CHALLENGED
D/HttpClient(10941): Proxy auth state: UNCHALLENGED
D/Wire    (10941): http-outgoing-0 >> "PUT /dav/otheruser@xxxxxxx.xx/MyCal/20150408T170109Z-10941_4933402f77a06876.ics HTTP/1.1[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "If-None-Match: *[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "Content-Type: text/calendar[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "Content-Length: 4006[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "Host: mother.xxxxxxx.xx[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "User-Agent: DAVdroid/0.7.2[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "Authorization: Basic [\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:VCALENDAR[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "VERSION:2.0[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "PRODID:-//bitfire web engineering//DAVdroid 0.7.2 (ical4j 1.0.x)//EN[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:VEVENT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTAMP:20150408T170109Z[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "UID:20150408T170109Z-10941@4933402f77a06876[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART;TZID=Europe/Brussels:20150408T130000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTEND;TZID=Europe/Brussels:20150408T140000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "SUMMARY:NewEvent by OtherUset[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "STATUS:CONFIRMED[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "ORGANIZER:mailto:otheruser@xxxxxxx.xx[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=CHAIR;PARTSTAT=ACCEPTED:mailto:otheruser@ga[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> " mboa.eu[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "LAST-MODIFIED:20150408T170109Z[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:VALARM[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TRIGGER:-PT15M[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "ACTION:DISPLAY[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DESCRIPTION:NewEvent by OtherUset[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:VALARM[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:VEVENT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:VTIMEZONE[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZID:Europe/Brussels[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZURL:http://tzurl.org/zoneinfo/Europe/Brussels[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "X-LIC-LOCATION:Europe/Brussels[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:DAYLIGHT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0200[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:CEST[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19810329T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:DAYLIGHT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0200[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:CET[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19961027T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+001730[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+001730[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:BMT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:18800101T000000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:18800101T000000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+001730[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:WET[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:18920501T120000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:18920501T120000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:CET[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19141108T000000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19141108T000000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:DAYLIGHT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0200[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:CEST[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19160501T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19160501T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19170416T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19180415T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19400520T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19430329T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19440403T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19450402T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19460519T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19770403T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19780402T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19790401T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19800406T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:DAYLIGHT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0200[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:CET[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19161001T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19161001T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19170917T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19180916T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19421102T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19431004T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19440917T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19450916T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19461007T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19770925T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19781001T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19790930T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19800928T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19810927T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19820926T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19830925T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19840930T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19850929T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19860928T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19870927T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19880925T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19890924T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19900930T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19910929T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19920927T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19930926T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19940925T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19950924T030000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:WET[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19181111T130000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19181111T130000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19191005T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19201024T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19211026T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19221008T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19231007T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19241005T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19251004T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19261003T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19271002T010000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19281007T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19291006T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19301005T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19311004T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19321002T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19331008T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19341007T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19351006T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19361004T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19371003T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19381002T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19391119T040000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:DAYLIGHT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:WEST[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19190301T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19190301T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19200214T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19210314T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19220325T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19230421T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19240329T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19250404T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19260417T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19270409T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19280414T230000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19290421T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19300413T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19310419T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19320403T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19330326T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19340408T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19350331T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19360419T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19370404T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19380327T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19390416T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19400225T020000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:DAYLIGHT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:DAYLIGHT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0200[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0200[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:CEST[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19440903T000000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19440903T000000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:DAYLIGHT[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "BEGIN:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETFROM:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZOFFSETTO:+0100[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "TZNAME:CET[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "DTSTART:19770101T000000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "RDATE:19770101T000000[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:STANDARD[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:VTIMEZONE[\r][\n]"
D/Wire    (10941): http-outgoing-0 >> "END:VCALENDAR[\r][\n]"
D/Wire    (10941): http-outgoing-0 << "HTTP/1.1 302 Found[\r][\n]"
D/Wire    (10941): http-outgoing-0 << "Date: Wed, 08 Apr 2015 17:01:19 GMT[\r][\n]"
D/Wire    (10941): http-outgoing-0 << "Content-Length: 0[\r][\n]"
D/Wire    (10941): http-outgoing-0 << "[\r][\n]"
D/HttpClient(10941): Connection can be kept alive indefinitely
D/HttpClient(10941): Authentication succeeded
E/davdroid.DavRedirectStrategy(10941): Received redirection without Location header, ignoring
D/HttpClient(10941): http-outgoing-0: Shutdown connection
D/HttpClient(10941): Connection discarded
D/HttpClient(10941): http-outgoing-0: Close connection
D/HttpClient(10941): Connection released: [id: 0][route: HttpRoute[{s}->https://mother.xxxxxxx.xx:443]][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 3]
W/davdroid.DavSyncAdapter(10941): Soft HTTP error 302 (Android will try again later)
W/davdroid.DavSyncAdapter(10941): at.bitfire.davdroid.webdav.HttpException: 302 Found
W/davdroid.DavSyncAdapter(10941): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:419)
W/davdroid.DavSyncAdapter(10941): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:393)
W/davdroid.DavSyncAdapter(10941): 	at at.bitfire.davdroid.webdav.WebDavResource.put(WebDavResource.java:370)
W/davdroid.DavSyncAdapter(10941): 	at at.bitfire.davdroid.resource.RemoteCollection.add(RemoteCollection.java:163)
W/davdroid.DavSyncAdapter(10941): 	at at.bitfire.davdroid.syncadapter.SyncManager.pushNew(SyncManager.java:143)
W/davdroid.DavSyncAdapter(10941): 	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:49)
W/davdroid.DavSyncAdapter(10941): 	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:146)
W/davdroid.DavSyncAdapter(10941): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
I/davdroid.DavSyncAdapter(10941): Sync complete for com.android.calendar
D/HttpClient(10941): Connection manager is shutting down
D/HttpClient(10941): Connection manager shut down
```

My Zimbra server gets the following log:

```
2015-04-08 19:05:37,634 INFO  [qtp509886383-597016:https://aaa.aaa.aaa.aaa:443/dav/otheruser@xxxxxxx.xx/MyCal/20150408T170528Z-10941_4933402f77a06876.ics] [aname=otheruser@xxxxxxx.xx;ip=212.233.58.49;ua=DAVdroid/0.7.2;] FileUploadServlet - saveUpload(): received Upload: { accountId=888cc41c-44ba-4417-91cd-610c0f9fb45d, time=Wed Apr 08 19:05:37 CEST 2015, size=4006, uploadId=7cc1b01e-b163-4851-a32d-59d09e8a9819:1d4f0474-0e0f-4fe5-946d-2b43dac9c891, name=null, path=null }
2015-04-08 19:05:37,675 INFO  [qtp509886383-597018:https://127.0.1.1:443/dav/mainuser@xxxxxxx.xx/MyCal/20150408T170528Z-10941_4933402f77a06876.ics] [aname=otheruser@xxxxxxx.xx;ip=127.0.0.1;ua=Jakarta Commons-HttpClient/3.1;] FileUploadServlet - saveUpload(): received Upload: { accountId=888cc41c-44ba-4417-91cd-610c0f9fb45d, time=Wed Apr 08 19:05:37 CEST 2015, size=4006, uploadId=7cc1b01e-b163-4851-a32d-59d09e8a9819:52cb5052-3299-43b3-8755-fdc1f8bb5944, name=null, path=null }
2015-04-08 19:05:37,677 INFO  [qtp509886383-597018:https://127.0.1.1:443/dav/mainuser@xxxxxxx.xx/MyCal/20150408T170528Z-10941_4933402f77a06876.ics] [aname=otheruser@xxxxxxx.xx;ip=127.0.0.1;ua=Jakarta Commons-HttpClient/3.1;] dav - sending redirect
2015-04-08 19:05:37,677 INFO  [qtp509886383-597018:https://127.0.1.1:443/dav/mainuser@xxxxxxx.xx/MyCal/20150408T170528Z-10941_4933402f77a06876.ics] [aname=otheruser@xxxxxxx.xx;ip=127.0.0.1;ua=Jakarta Commons-HttpClient/3.1;] dav - sending http error 302 because: wrong url - redirecting to:
https://mother.xxxxxx.xx:443/dav/mainuser@xxxxxxx.xx/MyCal/20150408T170528Z-10941@4933402f77a06876.ics
```

Thanks a lot...

Carlos.

**Comment by rfc2822** [comment]
Hello, thanks for your extensive and useful issue report (with logs!).

```
D/Wire    (10941): http-outgoing-0 << "HTTP/1.1 302 Found[\r][\n]"
D/Wire    (10941): http-outgoing-0 << "Date: Wed, 08 Apr 2015 17:01:19 GMT[\r][\n]"
D/Wire    (10941): http-outgoing-0 << "Content-Length: 0[\r][\n]"
D/Wire    (10941): http-outgoing-0 << "[\r][\n]"
```

indicates that Zimbra sends a redirection without a `Location` header. How shall DAVdroid know where the redirection points to when there is no `Location` header?

Is there any special reason why you have reported this to DAVdroid and not to Zimbra? In my opinion, this is a Zimbra issue.

**Comment by carlosgds** [comment]
Hi...
Oh I missed that bit! The log is clear on that point !
I thought (wrongly it seems) DAVdroid might redirect wrongly, because:
 * redirection works for non-shared calendars
 * the Zimbra-log shows the redirection destination

So Zimbra seems to be the problem - and I was told that our Zimbra install was updated recently! Next time I will try to gather all the facts before posting an issue ;-))

Thank again...
Carlos.

**Comment by rfc2822** [comment]
Ok, maybe you can post a link here to the Zimbra issue report, in case there's anything related to DAVdroid.

**Comment by carlosgds** [comment]
Good idea...
Waiting for the Zimbra forum-moderator to "accept* the issue... 
Carlos.

**Comment by rfc2822** [comment]
Thanks, I'll close this for now. If something is wrong on DAVdroid side, please post here again.
