### ISSUE TITLE
Davdroid crashes while synchronising contacts when Linphone is installed and creates a contact connection

### ISSUE THREAD

**Issue by horas13** [bitfireAT/davdroid#506]
While Davdroid usually works flawlessly, I experience a crash when synchronising the contacts after installing Linphone on my Phone.
I think it might be related to the fact that Linphone somehow creates a connection to existing contacts that are being synced via Davdroid and adds sip-addresses which somehow lead to a crash when Davdroid tries to do the synchronisation. If I uninstall Linphone, remove the Davdroid account  and create the Davdroid account with the same URL again, it works again (until I install Linpone again).

Here a few details:
Phone: OnePlus One with CyanogenOS (Andrdoid 4.4.4)
Davdroid 0.7.7
Carddav-Server: Owncloud 8.0.3

Debug log (I think this is the relevant part)

```
I/davdroid.DavSyncAdapter(26412): Performing sync for authority com.android.contacts
D/davdroid.DavSyncAdapter(26412): Creating new DavHttpClientV/davdroid.TlsSniSocketFactory(26412): Setting allowed TLS protocols: TLSv1, TLSv1.1, TLSv1.2
V/davdroid.TlsSniSocketFactory(26412): Setting allowed TLS ciphers: TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_RSA_EXPORT_WITH_RC4_40_MD5, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, SSL_DHE_DSS_WITH_DES_CBC_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_RC4_128_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_WITH_DES_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_DES_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA,
TLS_ECDH_RSA_WITH_RC4_128_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV, SSL_RSA_EXPORT_WITH_DES40_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_RC4_128_MD5, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA
D/davdroid.DavSyncAdapter(26412): Server supports VCard version 3.0
V/davdroid.URIUtils(26412): Normalized URL XXX_REMOVED_XXX
D/davdroid.WebDavResource(26412): Using preemptive authentication (not compatible with Digest auth)
I/davdroid.SyncManager(26412): Remotely removing 0 deleted resource(s) (if not changed)
I/davdroid.SyncManager(26412): Uploading 0 new resource(s) (if not existing)
I/davdroid.SyncManager(26412): Uploading 1 modified resource(s) (if not changed)
D/davdroid.resource(26412): Populating group from sourceid=? AND deleted=0 XXX_REMOVED_XXX
D/davdroid.resource(26412): Populating group from sourceid=? AND deleted=0 XXX_REMOVED_XXX
D/davdroid.DavSyncAdapter(26412): Closing httpClient
E/AndroidRuntime(26412): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime(26412): Process: at.bitfire.davdroid:sync, PID: 26412
E/AndroidRuntime(26412): java.lang.NullPointerException
E/AndroidRuntime(26412):        at at.bitfire.davdroid.resource.LocalAddressBook.populateSipAddress(LocalAddressBook.java:635)
E/AndroidRuntime(26412):        at at.bitfire.davdroid.resource.LocalAddressBook.populate(LocalAddressBook.java:251)
E/AndroidRuntime(26412):        at at.bitfire.davdroid.resource.LocalCollection.findById(LocalCollection.java:210)
E/AndroidRuntime(26412):        at at.bitfire.davdroid.syncadapter.SyncManager.pushDirty(SyncManager.java:168)
E/AndroidRuntime(26412):        at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:50)
E/AndroidRuntime(26412):        at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:146)E/AndroidRuntime(26412):        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

**Comment by helfio** [comment]
I'm having a similar issue. In my case I don't have Linphone app installed but I do have a couple of contacts with internet call directions user@sip.linphone.org in a field called 'Internet call' (I think; in spanish is 'Llamada por internet').

The server I use is owncloud 7.0.4 and it hasn't a field called anything similar to this internet call. After sync contacts this field is not synced. Maybe this is the problem.

This is my log:

```
06-22 14:22:19.765 D/AccountTypeManager(4302): Registering external account type=bitfire.at.davdroid, packageName=at.bitfire.davdroid
06-22 14:22:19.805 I/ActivityManager(927): Start proc at.bitfire.davdroid:sync for service at.bitfire.davdroid/.syncadapter.CalendarsSyncAdapterService: pid=6039 uid=10182 gids={50182, 3003}
06-22 14:22:19.912 I/davdroid.DavSyncAdapter(6039): Performing sync for authority com.android.contacts
06-22 14:22:19.912 D/davdroid.DavSyncAdapter(6039): Creating new DavHttpClient
06-22 14:22:20.016 I/davdroid.DavSyncAdapter(6039): Performing sync for authority com.android.calendar
06-22 14:22:20.029 V/davdroid.TlsSniSocketFactory(6039): Setting allowed TLS protocols: TLSv1, TLSv1.1, TLSv1.2
06-22 14:22:20.030 V/davdroid.TlsSniSocketFactory(6039): Setting allowed TLS ciphers: TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_RSA_EXPORT_WITH_RC4_40_MD5, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, SSL_DHE_DSS_WITH_DES_CBC_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_RC4_128_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_WITH_DES_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_DES_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_RC4_128_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV, SSL_RSA_EXPORT_WITH_DES40_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_RC4_128_MD5, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA
06-22 14:22:20.103 D/davdroid.DavSyncAdapter(6039): Server supports VCard version 3.0
06-22 14:22:20.114 V/davdroid.URIUtils(6039): Normalized URL https://$MY_SERVER.com/remote.php/carddav/addressbooks/$USER/contactos/ -> https://$MY_SERVER.com/remote.php/carddav/addressbooks/$USER/contactos/
06-22 14:22:20.121 D/davdroid.WebDavResource(6039): Using preemptive authentication (not compatible with Digest auth)
06-22 14:22:20.289 I/davdroid.SyncManager(6039): Remotely removing 0 deleted resource(s) (if not changed)
06-22 14:22:20.304 I/davdroid.SyncManager(6039): Uploading 0 new resource(s) (if not existing)
06-22 14:22:20.313 I/davdroid.SyncManager(6039): Uploading 2 modified resource(s) (if not changed)
06-22 14:22:20.495 D/davdroid.DavSyncAdapter(6039): Server supports VCard version 3.0
06-22 14:22:20.503 D/davdroid.DavSyncAdapter(6039): Closing httpClient
06-22 14:22:20.513 E/AndroidRuntime(6039): Process: at.bitfire.davdroid:sync, PID: 6039
06-22 14:22:20.513 E/AndroidRuntime(6039): 	at at.bitfire.davdroid.resource.LocalAddressBook.populateSipAddress(LocalAddressBook.java:635)
06-22 14:22:20.513 E/AndroidRuntime(6039): 	at at.bitfire.davdroid.resource.LocalAddressBook.populate(LocalAddressBook.java:251)
06-22 14:22:20.513 E/AndroidRuntime(6039): 	at at.bitfire.davdroid.resource.LocalCollection.findById(LocalCollection.java:220)
06-22 14:22:20.513 E/AndroidRuntime(6039): 	at at.bitfire.davdroid.syncadapter.SyncManager.pushDirty(SyncManager.java:168)
06-22 14:22:20.513 E/AndroidRuntime(6039): 	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:50)
06-22 14:22:20.513 E/AndroidRuntime(6039): 	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:146)
06-22 14:22:20.530 V/davdroid.URIUtils(6039): Normalized URL https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/defaultcalendar/ -> https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/defaultcalendar/
06-22 14:22:20.530 D/davdroid.WebDavResource(6039): Using preemptive authentication (not compatible with Digest auth)
06-22 14:22:20.535 V/davdroid.URIUtils(6039): Normalized URL https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/clases/ -> https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/clases/
06-22 14:22:20.535 D/davdroid.WebDavResource(6039): Using preemptive authentication (not compatible with Digest auth)
06-22 14:22:20.536 V/davdroid.URIUtils(6039): Normalized URL https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/exámenes/ -> https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/ex%C3%A1menes/
06-22 14:22:20.536 D/davdroid.WebDavResource(6039): Using preemptive authentication (not compatible with Digest auth)
06-22 14:22:20.537 V/davdroid.URIUtils(6039): Normalized URL https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/salidas/ -> https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/salidas/
06-22 14:22:20.538 D/davdroid.WebDavResource(6039): Using preemptive authentication (not compatible with Digest auth)
06-22 14:22:20.539 V/davdroid.URIUtils(6039): Normalized URL https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/iaa/ -> https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/iaa/
06-22 14:22:20.539 D/davdroid.WebDavResource(6039): Using preemptive authentication (not compatible with Digest auth)
06-22 14:22:20.540 V/davdroid.URIUtils(6039): Normalized URL https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/contact_birthdays/ -> https://$MY_SERVER.com/remote.php/caldav/calendars/$USER/contact_birthdays/
06-22 14:22:20.540 D/davdroid.WebDavResource(6039): Using preemptive authentication (not compatible with Digest auth)
06-22 14:22:20.588 I/davdroid.SyncManager(6039): Remotely removing 0 deleted resource(s) (if not changed)
06-22 14:22:20.597 I/davdroid.SyncManager(6039): Uploading 0 new resource(s) (if not existing)
06-22 14:22:20.620 I/CalendarProvider2(6066): No events to update: uri=content://com.android.calendar/events?account_type=bitfire.at.davdroid&account_name=$MY_SERVER.com&caller_is_syncadapter=true selection=_id IN (SELECT DISTINCT original_id FROM events WHERE original_id IS NOT NULL AND (dirty=1 OR deleted=1)) selectionArgs=null
06-22 14:22:20.625 I/davdroid.SyncManager(6039): Uploading 0 modified resource(s) (if not changed)
06-22 14:22:21.933 I/ActivityManager(927): Process at.bitfire.davdroid:sync (pid 6039) has died.
06-22 14:22:21.933 W/ActivityManager(927): Scheduling restart of crashed service at.bitfire.davdroid/.syncadapter.CalendarsSyncAdapterService in 1000ms
06-22 14:22:25.364 D/SFPerfTracer(266):        layers: (4:14) (DimLayer: 0:213)* (FocusedStackFrame: 0:5993)* (StatusBar: 0:20595) (NavigationBar: 0:4761) (com.android.systemui.ImageWallpaper: 0:2857) (DimLayer: 0:3009)* (DimLayer: 0:652)* (com.android.launcher/com.android.launcher2.Launcher: 0:28)* (com.android.systemui/com.android.systemui.recent.RecentsActivity: 0:11)* (Application Error: at.bitfire.davdroid:sync: 0:16)* (com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity: 0:26)* (thumbnail anim: 0:2)* (com.android.launcher/com.android.launcher2.Launcher: 1:9) 
06-22 14:22:26.164 D/AccountTypeManager(4302): Registering external account type=bitfire.at.davdroid, packageName=at.bitfire.davdroid
```

I hope this helps.
