### ISSUE TITLE
cannot add caldav account anymore with 0.8 beta1

### ISSUE THREAD

**Issue by jeekajoo** [bitfireAT/davdroid#512]
Hi,
davdroid crashes when trying to add a regular caldav account (with no vtodo).
it works with a carddav one.

using:
* client: davdroid 0.8 beta1
* server: owncloud 8
* os/phone: android omnirom 4.4.4 on nexus5

anonymized logcat:
```
I/davdroid.ResourceFinder( 7593): *** Starting CardDAV resource detection
D/davdroid.ResourceFinder( 7593): Looking up SRV records for _carddavs._tcp.own.domain.tld
I/davdroid.ResourceFinder( 7593): Looking up principal URL for service carddav; initial context: https://own.domain.tld/remote.php/caldav/
D/davdroid.WebDavResource( 7593): Using preemptive authentication (not compatible with Digest auth)
V/davdroid.URIUtils( 7593): Normalized URL /.well-known/carddav -> /.well-known/carddav
D/davdroid.ResourceFinder( 7593): Well-known carddav service detection failed with HTTP error
D/davdroid.ResourceFinder( 7593): at.bitfire.davdroid.webdav.HttpException: 403 Forbidden
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:431)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:405)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:286)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:281)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:63)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:120)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:98)
D/davdroid.ResourceFinder( 7593): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
D/davdroid.ResourceFinder( 7593): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
D/davdroid.ResourceFinder( 7593): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
D/davdroid.ResourceFinder( 7593): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
D/davdroid.ResourceFinder( 7593): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
D/davdroid.ResourceFinder( 7593): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
D/davdroid.ResourceFinder( 7593): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
D/davdroid.ResourceFinder( 7593): 	at java.lang.Thread.run(Thread.java:811)
D/davdroid.ResourceFinder( 7593): Well-known service detection failed, trying initial context path https://own.domain.tld/remote.php/caldav/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/ -> /remote.php/caldav/
D/davdroid.WebDavResource( 7593): Processing multi-status element: https://own.domain.tld/remote.php/caldav/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/principals/johndoe/ -> /remote.php/caldav/principals/johndoe/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/principals/johndoe/ -> /remote.php/caldav/principals/johndoe/
I/davdroid.ResourceFinder( 7593): Principal URL found from initial context path: /remote.php/caldav/principals/johndoe/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/principals/johndoe/ -> /remote.php/caldav/principals/johndoe/
D/davdroid.WebDavResource( 7593): Processing multi-status element: https://own.domain.tld/remote.php/caldav/principals/johndoe/
I/davdroid.ResourceFinder( 7593): *** Starting CalDAV resource detection
D/davdroid.ResourceFinder( 7593): Looking up SRV records for _caldavs._tcp.own.domain.tld
I/davdroid.ResourceFinder( 7593): Looking up principal URL for service caldav; initial context: https://own.domain.tld/remote.php/caldav/
D/davdroid.WebDavResource( 7593): Using preemptive authentication (not compatible with Digest auth)
V/davdroid.URIUtils( 7593): Normalized URL /.well-known/caldav -> /.well-known/caldav
D/davdroid.ResourceFinder( 7593): Well-known caldav service detection failed with HTTP error
D/davdroid.ResourceFinder( 7593): at.bitfire.davdroid.webdav.HttpException: 403 Forbidden
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:431)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:405)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:286)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:281)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:110)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:120)
D/davdroid.ResourceFinder( 7593): 	at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:98)
D/davdroid.ResourceFinder( 7593): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
D/davdroid.ResourceFinder( 7593): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
D/davdroid.ResourceFinder( 7593): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
D/davdroid.ResourceFinder( 7593): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
D/davdroid.ResourceFinder( 7593): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
D/davdroid.ResourceFinder( 7593): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
D/davdroid.ResourceFinder( 7593): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
D/davdroid.ResourceFinder( 7593): 	at java.lang.Thread.run(Thread.java:811)
D/davdroid.ResourceFinder( 7593): Well-known service detection failed, trying initial context path https://own.domain.tld/remote.php/caldav/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/ -> /remote.php/caldav/
D/davdroid.WebDavResource( 7593): Processing multi-status element: https://own.domain.tld/remote.php/caldav/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/principals/johndoe/ -> /remote.php/caldav/principals/johndoe/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/principals/johndoe/ -> /remote.php/caldav/principals/johndoe/
I/davdroid.ResourceFinder( 7593): Principal URL found from initial context path: /remote.php/caldav/principals/johndoe/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/principals/johndoe/ -> /remote.php/caldav/principals/johndoe/
D/davdroid.WebDavResource( 7593): Processing multi-status element: https://own.domain.tld/remote.php/caldav/principals/johndoe/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/calendars/johndoe/ -> /remote.php/caldav/calendars/johndoe/
I/davdroid.ResourceFinder( 7593): Found calendar home set: /remote.php/caldav/calendars/johndoe/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/calendars/johndoe/ -> /remote.php/caldav/calendars/johndoe/
D/davdroid.WebDavResource( 7593): Processing multi-status element: https://own.domain.tld/remote.php/caldav/calendars/johndoe/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/calendars/johndoe/personal/ -> /remote.php/caldav/calendars/johndoe/personal/
D/davdroid.WebDavResource( 7593): Processing multi-status element: https://own.domain.tld/remote.php/caldav/calendars/johndoe/personal/
I/Configurator( 7593): ical4j.properties not found.
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/calendars/johndoe/contact_birthdays/ -> /remote.php/caldav/calendars/johndoe/contact_birthdays/
D/davdroid.WebDavResource( 7593): Processing multi-status element: https://own.domain.tld/remote.php/caldav/calendars/johndoe/contact_birthdays/
V/davdroid.URIUtils( 7593): Normalized URL /remote.php/caldav/calendars/johndoe/outbox/ -> /remote.php/caldav/calendars/johndoe/outbox/
D/davdroid.WebDavResource( 7593): Processing multi-status element: https://own.domain.tld/remote.php/caldav/calendars/johndoe/outbox/
I/davdroid.ResourceFinder( 7593): Found calendar: /remote.php/caldav/calendars/johndoe/personal/
I/davdroid.ResourceFinder( 7593): Found calendar: /remote.php/caldav/calendars/johndoe/contact_birthdays/
W/ResourceType( 7593): Failure getting entry for 0x7f03000d (t=2 e=13) in package 0 (error -75)
D/AndroidRuntime( 7593): Shutting down VM
E/AndroidRuntime( 7593): FATAL EXCEPTION: main
E/AndroidRuntime( 7593): Process: at.bitfire.davdroid:sync, PID: 7593
E/AndroidRuntime( 7593): android.content.res.Resources$NotFoundException: Resource ID #0x7f03000d
E/AndroidRuntime( 7593): 	at android.content.res.Resources.getValue(Resources.java:1123)
E/AndroidRuntime( 7593): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2309)
E/AndroidRuntime( 7593): 	at android.content.res.Resources.getLayout(Resources.java:939)
E/AndroidRuntime( 7593): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
E/AndroidRuntime( 7593): 	at at.bitfire.davdroid.ui.setup.SelectCollectionsAdapter.getView(SelectCollectionsAdapter.java:153)
E/AndroidRuntime( 7593): 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
E/AndroidRuntime( 7593): 	at android.widget.AbsListView.obtainView(AbsListView.java:2257)
E/AndroidRuntime( 7593): 	at android.widget.ListView.makeAndAddView(ListView.java:1790)
E/AndroidRuntime( 7593): 	at android.widget.ListView.fillDown(ListView.java:691)
E/AndroidRuntime( 7593): 	at android.widget.ListView.fillFromTop(ListView.java:752)
E/AndroidRuntime( 7593): 	at android.widget.ListView.layoutChildren(ListView.java:1630)
E/AndroidRuntime( 7593): 	at android.widget.AbsListView.onLayout(AbsListView.java:2089)
E/AndroidRuntime( 7593): 	at android.view.View.layout(View.java:14824)
E/AndroidRuntime( 7593): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime( 7593): 	at android.view.View.layout(View.java:14824)
E/AndroidRuntime( 7593): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime( 7593): 	at android.view.View.layout(View.java:14824)
E/AndroidRuntime( 7593): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime( 7593): 	at android.view.View.layout(View.java:14824)
E/AndroidRuntime( 7593): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime( 7593): 	at android.view.View.layout(View.java:14824)
E/AndroidRuntime( 7593): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 7593): 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
E/AndroidRuntime( 7593): 	at android.view.View.layout(View.java:14824)
E/AndroidRuntime( 7593): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime( 7593): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime( 7593): 	at android.view.View.layout(View.java:14824)
E/AndroidRuntime( 7593): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 7593): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
E/AndroidRuntime( 7593): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
E/AndroidRuntime( 7593): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
E/AndroidRuntime( 7593): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
E/AndroidRuntime( 7593): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
E/AndroidRuntime( 7593): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime( 7593): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
E/AndroidRuntime( 7593): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/AndroidRuntime( 7593): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 7593): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 7593): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7593): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 7593): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7593): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 7593): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/ActivityManager(  807):   Force finishing activity at.bitfire.davdroid/.ui.setup.AddAccountActivity
W/ActivityManager(  807): Activity pause timeout for ActivityRecord{656b3af0 u0 at.bitfire.davdroid/.ui.setup.AddAccountActivity t114 f}
I/Process ( 7593): Sending signal. PID: 7593 SIG: 9
I/ActivityManager(  807): Process at.bitfire.davdroid:sync (pid 7593) has died.
I/WindowState(  807): WIN DEATH: Window{65e55300 u0 at.bitfire.davdroid/at.bitfire.davdroid.ui.MainActivity}
I/WindowState(  807): WIN DEATH: Window{65eb54f8 u0 at.bitfire.davdroid/at.bitfire.davdroid.ui.setup.AddAccountActivity}
```

thanks
J.

**Comment by rfc2822** [comment]
How can you add an OwnCloud 8 account without VTODO? In my OwnCloud 8 installation (only Contacts and Calendars enabled, no Tasks!), and it tells DAVdroid:

```
           <cal:supported-calendar-component-set>
                <cal:comp name="VEVENT"/>
                <cal:comp name="VTODO"/>
                <cal:comp name="VJOURNAL"/>
            </cal:supported-calendar-component-set>
```

**Comment by jeekajoo** [comment]
Well I don't know.
The thing is, I try to setup the caldav account I had before. It looks like it finds 2:
I/davdroid.ResourceFinder( 7593): Found calendar: /remote.php/caldav/calendars/johndoe/personal/
I/davdroid.ResourceFinder( 7593): Found calendar: /remote.php/caldav/calendars/johndoe/contact_birthdays/
and it crashes before I can select anything. Used to work with previous version.

On my owncloud, I have the "tasks" app. I have no idea if the tasks on it are supposed to be available through the caldav server as VTODO. Do you know that?

**Comment by rfc2822** [comment]
Can you please try https://github.com/bitfireAT/davdroid/releases/tag/v0.8-beta2?

**Comment by jeekajoo** [comment]
awesome. it works. and I can see my tasks that were registered in owncloud tasks app.
