### ISSUE TITLE
java.lang.NullPointerException in in at.bitfire.davdroid.ui.setup.SelectCollectionsAdapter.<init>

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/davdroid#548]
From Play Store
DAVdroid 0.8.0
Android 4.4
HUAWEI G7-L01 (hwG7-L01)

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{at.bitfire.davdroid/at.bitfire.davdroid.ui.setup.AddAccountActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3930)
at android.app.ActivityThread.access$1200(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5336)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at at.bitfire.davdroid.ui.setup.SelectCollectionsAdapter.<init>(SelectCollectionsAdapter.java:59)
at at.bitfire.davdroid.ui.setup.SelectCollectionsFragment.onViewCreated(SelectCollectionsFragment.java:57)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:910)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1071)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1053)
at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1862)
at android.app.Activity.performCreate(Activity.java:5306)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
... 12 more
```

**Comment by rfc2822** [comment]
Duplicate of #543, fixed
