### ISSUE TITLE
java.lang.SecurityException in in android.os.Parcel.readException

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/davdroid#550]
From Play Store
DAVdroid 0.8
Android 5.1
Nexus 7 (flo)

"Was trying to sync tasks, using Tasks app."

```
java.lang.SecurityException: Permission Denial: opening provider org.dmfs.provider.tasks.TaskProvider from ProcessRecord{3bdf1422 23133:at.bitfire.davdroid:sync/u0a210} (pid=23133, uid=10210) requires org.dmfs.permission.READ_TASKS or org.dmfs.permission.WRITE_TASKS
at android.os.Parcel.readException(Parcel.java:1546)
at android.os.Parcel.readException(Parcel.java:1499)
at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3314)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:4624)
at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2453)
at android.content.ContentResolver.acquireProvider(ContentResolver.java:1426)
at android.content.ContentResolver.acquireContentProviderClient(ContentResolver.java:1489)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:257)
```

**Comment by rfc2822** [comment]
Seems to be an exception in Android code, caused by syncing tasks without permission (i.e. when Tasks is installed *after* DAVdroid).
