### ISSUE TITLE
Can't find calendars on server with "SSL proxy"

### ISSUE THREAD

**Issue by uvok** [bitfireAT/davdroid#565]
Some webhosters don't allow the user to use SSL certificates in cheaper webhosting packages, instead using an ssl proxy were content is accessed via another domain, e.g. http://ssl.webpack.de/ (for Hosteurope). The URL dav.myserver.tld/cal.php would become http://ssl.webpack.de/dav.myserver.tld/cal.php if accessed via the SSL proxy.

I could access the calendar on my server (Baïkal) via the HTTP URL, but if I want to access it via the SSL proxy URL, Davdroid complains about missing DAV capabilities (no CalDAV/CardDAV service available at this location)

Debug log for failure (HTTPS server):

    06-28 13:50:38.163  14736-14736/at.bitfire.davdroid:sync I/davdroid.QueryServer﹕ onCreateLoader
    06-28 13:50:38.203  14736-17292/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ *** Starting CardDAV resource detection
    06-28 13:50:38.244  14736-17292/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Looking up SRV records for _carddavs._tcp.ssl.webpack.de
    06-28 13:50:38.304  14736-14736/at.bitfire.davdroid:sync W/EGL_emulation﹕ eglSurfaceAttrib not implemented
    06-28 13:50:38.514  14736-17292/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Looking up principal URL for service carddav; initial context: https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default
    06-28 13:50:38.583  14736-17292/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /.well-known/carddav -> /.well-known/carddav
    06-28 13:50:41.224  14736-17292/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Well-known carddav service detection failed with HTTP error
        at.bitfire.davdroid.webdav.HttpException: 502 Bad Gateway
                at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:430)
                at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:404)
                at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:285)
                at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:278)
                at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:61)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:117)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:95)
                at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
                at android.os.AsyncTask$2.call(AsyncTask.java:287)
                at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                at java.lang.Thread.run(Thread.java:856)
    06-28 13:50:41.234  14736-17292/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Well-known service detection failed, trying initial context path https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default
    06-28 13:50:42.123  14736-14740/at.bitfire.davdroid:sync D/dalvikvm﹕ GC_CONCURRENT freed 1172K, 16% free 6617K/7852K, paused 7ms+25ms, total 278ms
    06-28 13:50:46.234  14736-17292/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/default/ -> /cal.php/calendars/myuser/default/
    06-28 13:50:46.234  14736-17292/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: https://ssl.webpack.de/cal.php/calendars/myuser/default/
    06-28 13:50:46.264  14736-17292/at.bitfire.davdroid:sync D/davdroid.URIUtils﹕ Appended trailing slash to collection https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default -> https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:50:46.284  14736-17292/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Couldn't find current-user-principal for service carddav, assuming initial context path is principal path
    06-28 13:50:49.234  14736-14740/at.bitfire.davdroid:sync D/dalvikvm﹕ GC_CONCURRENT freed 1293K, 17% free 6626K/7984K, paused 7ms+18ms, total 371ms
    06-28 13:50:49.733  14736-17292/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/default/ -> /cal.php/calendars/myuser/default/
    06-28 13:50:49.753  14736-17292/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: https://ssl.webpack.de/cal.php/calendars/myuser/default/
    06-28 13:50:49.783  14736-17292/at.bitfire.davdroid:sync D/davdroid.URIUtils﹕ Appended trailing slash to collection https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default -> https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:50:49.793  14736-17292/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ *** Starting CalDAV resource detection
    06-28 13:50:49.793  14736-17292/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Looking up SRV records for _caldavs._tcp.ssl.webpack.de
    06-28 13:50:49.843  14736-17292/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Looking up principal URL for service caldav; initial context: https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default
    06-28 13:50:49.873  14736-17292/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /.well-known/caldav -> /.well-known/caldav
    06-28 13:50:51.414  14736-17292/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Well-known caldav service detection failed with HTTP error
        at.bitfire.davdroid.webdav.HttpException: 502 Bad Gateway
                at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:430)
                at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:404)
                at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:285)
                at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:278)
                at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:108)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:117)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:95)
                at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
                at android.os.AsyncTask$2.call(AsyncTask.java:287)
                at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                at java.lang.Thread.run(Thread.java:856)
    06-28 13:50:51.414  14736-17292/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Well-known service detection failed, trying initial context path https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default
    06-28 13:50:56.133  14736-14740/at.bitfire.davdroid:sync D/dalvikvm﹕ GC_CONCURRENT freed 1254K, 17% free 6674K/7996K, paused 8ms+21ms, total 340ms
    06-28 13:50:56.244  14736-17292/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/default/ -> /cal.php/calendars/myuser/default/
    06-28 13:50:56.254  14736-17292/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: https://ssl.webpack.de/cal.php/calendars/myuser/default/
    06-28 13:50:56.274  14736-17292/at.bitfire.davdroid:sync D/davdroid.URIUtils﹕ Appended trailing slash to collection https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default -> https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:50:56.274  14736-17292/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Couldn't find current-user-principal for service caldav, assuming initial context path is principal path
    06-28 13:50:59.184  14736-17292/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/default/ -> /cal.php/calendars/myuser/default/
    06-28 13:50:59.193  14736-17292/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: https://ssl.webpack.de/cal.php/calendars/myuser/default/
    06-28 13:50:59.214  14736-17292/at.bitfire.davdroid:sync D/davdroid.URIUtils﹕ Appended trailing slash to collection https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default -> https://ssl.webpack.de/dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:50:59.284  14736-17292/at.bitfire.davdroid:sync E/davdroid.ServerInfoLoader﹕ DAV error while querying server info
        at.bitfire.davdroid.webdav.DavIncapableException: Invalid DAV response: No CalDAV-/CardDAV service is available at this location.
                at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:178)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:117)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:95)
                at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
                at android.os.AsyncTask$2.call(AsyncTask.java:287)
                at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                at java.lang.Thread.run(Thread.java:856)

Debug log for success (HTTP):    

    06-28 13:53:37.683  14736-14736/at.bitfire.davdroid:sync W/EGL_emulation﹕ eglSurfaceAttrib not implemented
    06-28 13:53:39.413  14736-14736/at.bitfire.davdroid:sync W/EGL_emulation﹕ eglSurfaceAttrib not implemented
    06-28 13:53:40.094  14736-14736/at.bitfire.davdroid:sync W/EGL_emulation﹕ eglSurfaceAttrib not implemented
    06-28 13:53:43.563  14736-14736/at.bitfire.davdroid:sync I/davdroid.QueryServer﹕ onCreateLoader
    06-28 13:53:43.653  14736-18275/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ *** Starting CardDAV resource detection
    06-28 13:53:43.683  14736-14736/at.bitfire.davdroid:sync W/EGL_emulation﹕ eglSurfaceAttrib not implemented
    06-28 13:53:43.733  14736-18275/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Looking up SRV records for _carddavs._tcp.dav.myserver.tld
    06-28 13:53:43.793  14736-18275/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Looking up principal URL for service carddav; initial context: http://dav.myserver.tld/cal.php/calendars/myuser/default
    06-28 13:53:43.943  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /.well-known/carddav -> /.well-known/carddav
    06-28 13:53:45.104  14736-14740/at.bitfire.davdroid:sync D/dalvikvm﹕ GC_CONCURRENT freed 1290K, 17% free 6700K/8056K, paused 12ms+34ms, total 367ms
    06-28 13:53:45.523  14736-18275/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Well-known carddav service detection failed with HTTP error
        at.bitfire.davdroid.webdav.HttpException: 405 Method Not Allowed
                at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:430)
                at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:404)
                at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:285)
                at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:278)
                at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:61)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:117)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:95)
                at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
                at android.os.AsyncTask$2.call(AsyncTask.java:287)
                at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                at java.lang.Thread.run(Thread.java:856)
    06-28 13:53:45.523  14736-18275/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Well-known service detection failed, trying initial context path http://dav.myserver.tld/cal.php/calendars/myuser/default
    06-28 13:53:48.523  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/default/ -> /cal.php/calendars/myuser/default/
    06-28 13:53:48.523  14736-18275/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: http://dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:53:48.563  14736-18275/at.bitfire.davdroid:sync D/davdroid.URIUtils﹕ Appended trailing slash to collection http://dav.myserver.tld/cal.php/calendars/myuser/default -> http://dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:53:48.603  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/principals/myuser/ -> /cal.php/principals/myuser/
    06-28 13:53:48.623  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/principals/myuser/ -> /cal.php/principals/myuser/
    06-28 13:53:48.623  14736-18275/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Principal URL found from initial context path: /cal.php/principals/myuser/
    06-28 13:53:51.063  14736-14740/at.bitfire.davdroid:sync D/dalvikvm﹕ GC_CONCURRENT freed 1348K, 18% free 6680K/8096K, paused 7ms+18ms, total 332ms
    06-28 13:53:52.034  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/principals/myuser/ -> /cal.php/principals/myuser/
    06-28 13:53:52.044  14736-18275/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: http://dav.myserver.tld/cal.php/principals/myuser/
    06-28 13:53:52.064  14736-18275/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ *** Starting CalDAV resource detection
    06-28 13:53:52.064  14736-18275/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Looking up SRV records for _caldavs._tcp.dav.myserver.tld
    06-28 13:53:52.094  14736-18275/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Looking up principal URL for service caldav; initial context: http://dav.myserver.tld/cal.php/calendars/myuser/default
    06-28 13:53:52.134  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /.well-known/caldav -> /.well-known/caldav
    06-28 13:53:53.294  14736-18275/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Well-known caldav service detection failed with HTTP error
        at.bitfire.davdroid.webdav.HttpException: 405 Method Not Allowed
                at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:430)
                at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:404)
                at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:285)
                at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:278)
                at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:108)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:117)
                at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:95)
                at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
                at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
                at android.os.AsyncTask$2.call(AsyncTask.java:287)
                at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                at java.lang.Thread.run(Thread.java:856)
    06-28 13:53:53.304  14736-18275/at.bitfire.davdroid:sync D/davdroid.ResourceFinder﹕ Well-known service detection failed, trying initial context path http://dav.myserver.tld/cal.php/calendars/myuser/default
    06-28 13:53:56.144  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/default/ -> /cal.php/calendars/myuser/default/
    06-28 13:53:56.144  14736-18275/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: http://dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:53:56.184  14736-18275/at.bitfire.davdroid:sync D/davdroid.URIUtils﹕ Appended trailing slash to collection http://dav.myserver.tld/cal.php/calendars/myuser/default -> http://dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:53:56.194  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/principals/myuser/ -> /cal.php/principals/myuser/
    06-28 13:53:56.224  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/principals/myuser/ -> /cal.php/principals/myuser/
    06-28 13:53:56.234  14736-18275/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Principal URL found from initial context path: /cal.php/principals/myuser/
    06-28 13:53:56.773  14736-14740/at.bitfire.davdroid:sync D/dalvikvm﹕ GC_CONCURRENT freed 1341K, 18% free 6661K/8096K, paused 7ms+17ms, total 232ms
    06-28 13:53:59.423  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/principals/myuser/ -> /cal.php/principals/myuser/
    06-28 13:53:59.423  14736-18275/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: http://dav.myserver.tld/cal.php/principals/myuser/
    06-28 13:53:59.453  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/ -> /cal.php/calendars/myuser/
    06-28 13:53:59.463  14736-18275/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Found calendar home set: /cal.php/calendars/myuser/
    06-28 13:54:02.753  14736-14740/at.bitfire.davdroid:sync D/dalvikvm﹕ GC_CONCURRENT freed 1286K, 18% free 6690K/8072K, paused 6ms+19ms, total 322ms
    06-28 13:54:06.034  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/ -> /cal.php/calendars/myuser/
    06-28 13:54:06.044  14736-18275/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: http://dav.myserver.tld/cal.php/calendars/myuser/
    06-28 13:54:06.094  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/default/ -> /cal.php/calendars/myuser/default/
    06-28 13:54:06.104  14736-18275/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: http://dav.myserver.tld/cal.php/calendars/myuser/default/
    06-28 13:54:06.164  14736-18275/at.bitfire.davdroid:sync V/davdroid.URIUtils﹕ Normalized URL /cal.php/calendars/myuser/outbox/ -> /cal.php/calendars/myuser/outbox/
    06-28 13:54:06.174  14736-18275/at.bitfire.davdroid:sync D/davdroid.WebDavResource﹕ Processing multi-status element: http://dav.myserver.tld/cal.php/calendars/myuser/outbox/
    06-28 13:54:06.204  14736-18275/at.bitfire.davdroid:sync I/davdroid.ResourceFinder﹕ Found calendar: /cal.php/calendars/myuser/default/
    06-28 13:54:06.224  14736-14736/at.bitfire.davdroid:sync E/ActivityThread﹕ Failed to find provider info for org.dmfs.tasks

I could provide a test account on my server if needed.

**Comment by rfc2822** [comment]
This is a problem of Baïkal which doesn't support/isn't configured with the correct base path. See https://github.com/bitfireAT/davdroid/issues/223#issuecomment-43132214 for more information (or have a look into the Baïkal docs/community).
