### ISSUE TITLE
NullPointerException in populateSipAddress

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/davdroid#575]
From Play Store:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
at at.bitfire.davdroid.resource.LocalAddressBook.populateSipAddress(LocalAddressBook.java:638)
at at.bitfire.davdroid.resource.LocalAddressBook.populate(LocalAddressBook.java:249)
at at.bitfire.davdroid.resource.LocalCollection.findById(LocalCollection.java:220)
at at.bitfire.davdroid.syncadapter.SyncManager.pushDirty(SyncManager.java:163)
at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:49)
at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:137)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

Possibly related to #506

**Comment by rfc2822** [comment]
Duplicate of #506.
