### ISSUE TITLE
Error 400 - Sync BedeWork 3.7

### ISSUE THREAD

**Issue by Magalanez** [bitfireAT/davdroid#618]
I get error 400 HTTP in:
public void report(String query) throws IOException, HttpException, DavException {
		HttpReport report = new HttpReport(location, query);
		report.setHeader("Depth", "1");

		@Cleanup CloseableHttpResponse response = httpClient.execute(report, context); //This line I mean.
		if (response == null)
			throw new DavNoContentException();

		checkResponse(response);
		processMultiStatus(response);
}

I just tried davdroid with OwnCloud and it works. With Bedework v3.7 does not. Then, I used Sardine to test the conection and download ".ics" files and I see that it works fine with Sardine. Has any support to this server?

**Comment by devvv4ever** [comment]
I don't exactly know what you mean. You need to setup a server in a way that that it tells DAVdroid the correct paths to the caldav/carddav  resources for a given user. Best would be to use .well-known paths.

**Comment by rfc2822** [comment]
Is there any reason why you think the 400 error is caused by DAVdroid? Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

**Comment by Magalanez** [comment]
The error starts with "4xx" so I guess it's the client's fault-although I'm not sure.

08-26 09:37:18.591    1351-1449/at.bitfire.davdroid:sync E/davdroid.DavSyncAdapter﹕ Hard HTTP error 400
    at.bitfire.davdroid.webdav.HttpException: 400 Peticiï¿½n incorrecta
            at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:357)
            at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:327)
            at at.bitfire.davdroid.webdav.WebDavResource.report(WebDavResource.java:264)
            at at.bitfire.davdroid.resource.WebDavCollection.getMemberETags(WebDavCollection.java:86)
            at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:83)
            at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:137)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

URL: https://<myhost.com>/ucaldav/user/<myuser>/
Credentials are correct.

<uses-sdk
        android:minSdkVersion="14"
        android:targetSdkVersion="22" />

Running with Custom emulator, version 4.4.4 // API 19
Server: Bedework 3.7 EN
Version DavDROID: 0.8.3

The error occurs when I try to synchronize with the server. In the previous screens displayed correctly calendars.
