### ISSUE TITLE
Couldn't parse Multi-Status response on REPORT multi-get

### ISSUE THREAD

**Issue by qfvldaa2xn** [bitfireAT/davdroid#621]
I get following error:

```at.bitfire.davdroid.webdav.DavException: Invalid DAV response: Couldn't parse Multi-Status response on REPORT multi-get at at.bitfire.davdroid.webdav.WebDavResource.processMultiStatus(WebDavResource.java:380)...```

davdroid was just syncing fine before, but now I receive the error message. I already removed and added the account again. Doesn't resolve the issue.

On my radicale server I see that the last sync was today in the morning and all my last entries are in the contacts.vcf file. (Permissions and everything else is equal to the calendar file, where the sync is working fine.)

I haven't found a solution to this issue. Any idea?

**Comment by qfvldaa2xn** [comment]
I just tried to create a backup and then use a vcf with only one random contact on the server. Then it syncs fine again.

It seems that the error is in one of the contacts, right? Wired thing about it is that I only use davdroid with that vcf and I haven't touched the vcf on the server.

Removing the last two VCARDs where I made changes didn't help neither... Uff how do I find the error now in a file with around 200 contacts???

**Comment by qfvldaa2xn** [comment]
I just tried to create an empty vcf on the server and import the backup vcf on the phone. The import was successful, and then the first sync with the server is successful as well. So the vcf on the server (which was empty before the sync) has again the same size as the original vcf.

But with the next sync the issue is there again:
'''
at.bitfire.davdroid.webdav.DavException: Invalid DAV response: Couldn't parse Multi-Status response on REPORT multi-get at at.bitfire.davdroid.webdav.WebDavResource.processMultiStatus(WebDavResource.java:380)...
'''

**Comment by rfc2822** [comment]
It seems like the Radicale server has a problem with one of the contacts or its storage (thus the server error on REPORT). Is there any reason why you think this is related to DAVdroid?

**Comment by qfvldaa2xn** [comment]
To tell you the truth, I was not sure what the error means... And in the radicale debug I haven't seen an error. So I thought it is DAVdroid related.
